```{r abstract}
# automatically prints on new page
block_caption("Abstract", style = "Unnumbered Header")
```


The present study investigated whether exposure to linguistic diversity promotes gradient speech categorization and facilitates second language (L2) speech learning. Speech categorization, or the mapping of continuous acoustic signals onto discrete language units such as phonemes, is a core challenge in adult L2 speech acquisition. Some individuals show gradient patterns of speech categorization, in which the continuous nature of acoustic speech cues is retained in the mental representations of speech categories. Gradient categorization has been found to perceptual flexibility and multiple acoustic cue integration, which may be advantageous for learning new L2 phonemes. Exposure to linguistically diverse environments has been associated with gradient categorization and perceptual flexibility, and specific language experience may support L2 perception when learners have familiarity with phonemic contrasts similar to those in the target language. From these observations, I hypothesized that exposing learners to some form of specific “linguistic diversity” may push them towards gradient perception and the perceptual flexibility needed for efficient L2 speech category learning.

To test this hypothesis, three studies were conducted to explore the relationships among categorization gradiency, linguistic diversity, and L2 learning of the Japanese phonemic length contrasts in vowels (e.g., toru vs. tooru) and consonants (e.g., kata vs. katta). Study 1 assessed whether experiential linguistic diversity, measured with a Linguistic Diversity Questionnaire, predicted gradiency in L1 and L2 categorization, measured with a Visual Analog Scale (VAS) task. Study 2 manipulated linguistic diversity exposure through short-term perceptual discrimination training with naïve L1 monolingual English speakers (training on Japanese alone vs. Japanese and Modern Standard Arabic) and assessed changes in gradiency and L2 discrimination, measured with a perceptual discrimination task. Study 3 extended this training to L2 Japanese learners in a classroom setting and evaluated changes in gradiency, L2 discrimination, and L2 listening accuracy, measured with a Multiple-Choice Partial Dictation (MCPD) listening assessment.

Across all three studies, individual differences in categorization strategies were evident within and across participants, but neither experiential nor manipulated linguistic diversity significantly predicted nor affected gradiency. Additionally, naïve, but not classroom, learners improved in L2 learning outcomes following training, though learning was not modulated by the linguistic diversity condition. Overall, the results of the three studies did not support the hypothesis that exposure to specific linguistic diversity promotes gradient perception and the perceptual flexibility needed for efficient L2 speech category learning. Instead, the findings showcase the diversity of individual differences in categorization gradiency, highlight the phoneme- and context-specific nature of categorization behavior, and provide one of the first few within-participant comparisons of L1 and L2 categorization gradiency. The implications of the findings in the context of extant literature are that gradient categorization may be a stable trait, rather than manipulable by short-term exposure, and that the effects of linguistic diversity on perception and learning are likely to manifest over a longer time period than utilized in this study. This dissertation contributes to the fields of applied psycholinguistics and SLA by offering the first exploration into connecting gradient categorization, linguistic diversity, and L2 speech learning.

The full collection of study materials, including stimuli and task materials, raw and cleaned anonymized data, and data analysis code, can be found in the supplementary materials available through the following webpages: https://doi.org/10.17605/OSF.IO/M6T59 and https://app.gorilla.sc/openmaterials/1089564.

**Keywords**: gradient categorization, linguistic diversity, speech perception, perceptual learning, L2 speech learning, phonetic training
