---
title: "Study 2 VAS Bayesian hierarchical curvefitting"
author: "Chisom Obasih"
date: "May 2025"
subtitle: "Attempt to estimate 4-parameter logistic curve parameters from one-dimensional VAS data, estimate subject-continuum specific parameters and variance using Bayesian hierarchical curvefitting based on Sorensen et al., 2024)"


output: 
  pdf_document:
    latex_engine: xelatex
    includes:
      in_header: "/Users/chisomobasih/Exp-Research/General/wrap-code.tex"
editor_options: 
  chunk_output_type: inline
---

## Libraries
```{r load-libraries, message=FALSE}
suppressPackageStartupMessages(library(tidyverse))
library(janitor)
library(rio)
library(ggthemes)
library(ggpubr)
library(rstatix)
library(lmerTest)
library(psycho)
library(knitr)

library(conflicted)
# package to solve conflicts between functions of different packages that use the same name
# use dplyr for all functions in the case of conflict between packages, output suppressed
conflict_prefer_all("dplyr", quiet = TRUE)
# use lmerTest for the following functions in the case of conflict between packages
conflict_prefer("lmer", "lmerTest")

# avoid scientific notation
options(scipen = 999)

# library(tidyLPA)
# library(mclust)
# default package used to estimate profiles is mclust (MPlus is not installed on my computer)

# for Bayesian multivariate regression modeling
# installation of package rstan is required to run brms
library(brms)
library(tidybayes)
library(bayestestR)
library(parameters)
library(insight)

# fit data distributions
library(fitdistrplus)

library(flextable)
```

```{r conflicts, message=FALSE}
# conflicts that arise when running brm()
conflicts_prefer(brms::ar)
conflicts_prefer(flextable::as_image)
conflicts_prefer(ggpubr::border)
conflicts_prefer(janitor::chisq.test)
conflicts_prefer(purrr::compose)
conflicts_prefer(flextable::continuous_summary)
conflicts_prefer(tidyr::expand)
conflicts_prefer(lme4::factorize)
conflicts_prefer(janitor::fisher.test)
conflicts_prefer(ggpubr::font)
conflicts_prefer(flextable::footnote)
conflicts_prefer(lme4::golden)
conflicts_prefer(janitor::make_clean_names)
conflicts_prefer(brms::ngrps)
conflicts_prefer(tidyr::pack)
conflicts_prefer(janitor::remove_empty_cols)
conflicts_prefer(ggpubr::rotate)
conflicts_prefer(flextable::separate_header)
conflicts_prefer(lmerTest::step)
conflicts_prefer(tidyr::unpack)
conflicts_prefer(brms::kidney)# conflicts that arise when running brm()
conflicts_prefer(brms::ar)
conflicts_prefer(flextable::as_image)
conflicts_prefer(ggpubr::border)
conflicts_prefer(janitor::chisq.test)
conflicts_prefer(purrr::compose)
conflicts_prefer(flextable::continuous_summary)
conflicts_prefer(tidyr::expand)
conflicts_prefer(lme4::factorize)
conflicts_prefer(janitor::fisher.test)
conflicts_prefer(ggpubr::font)
conflicts_prefer(flextable::footnote)
conflicts_prefer(lme4::golden)
conflicts_prefer(janitor::make_clean_names)
conflicts_prefer(brms::ngrps)
conflicts_prefer(tidyr::pack)
conflicts_prefer(janitor::remove_empty_cols)
conflicts_prefer(ggpubr::rotate)
conflicts_prefer(flextable::separate_header)
conflicts_prefer(lmerTest::step)
conflicts_prefer(tidyr::unpack)
conflicts_prefer(brms::kidney)
conflicts_prefer(brms::dstudent_t)
conflicts_prefer(insight::get_data)
conflicts_prefer(bayestestR::hdi)
conflicts_prefer(purrr::map)
conflicts_prefer(brms::me)
conflicts_prefer(parameters::parameters)
conflicts_prefer(brms::pstudent_t)
conflicts_prefer(brms::qstudent_t)
conflicts_prefer(brms::rstudent_t)
conflicts_prefer(janitor::clean_names)
```

------------------------------------------------------------------------


## Read in data

```{r read-data, message = FALSE}
# load cleaned VAS dataframes
load("Rdata/study2_cleaned_vas.Rdata")

head(mld_filtered_matlab)

mld_filtered_matlab %>%
  group_by(pair, first_dim_step) %>%
  get_summary_stats(norm_response, show = c("mean", "sd"))
```


```{r set-up-brms}

# using the equations and stuff specified in Sorenson et al., 2024 (doi: https://doi.org/10.1177/09622802241242319)

# with a LOT of help from chatgpt to set this up with brms

# set 4 parameter logistic curve function
# 
logistic.formula <- bf(norm_response ~ min + (max - min) / (1 + exp(4 * slope / (max - min) * (X0 - first_dim_step))), # four parameters of min asymptote, max asymptote, slope as crossover point, and crossover point (X0)
  min + max + slope + X0 ~ 1 + (1 | ID/day/pair), # model hierarchical subject/continuum nested structure for each parameters 
  sigma ~ 1 + (1 | ID/day/pair), # model hierarchical subject/continuum nested structure for residual variance
  nl = TRUE) # non-linear

# set priors
logistic.priors <- c(
  prior(normal(10, 10), nlpar = "min", class = "b"), # center mean of min at 10 with sd 10
  prior(normal(90, 10), nlpar = "max", class = "b"), # center mean of max at 90 with sd 10
  prior(normal(40, 20), nlpar = "slope", class = "b"), # center mean of slope at 40 with sd 20 - very wide
  prior(normal(4, 1), nlpar = "X0", class = "b"), # center mean of crossover point at 4 with sd of 1
  prior(exponential(0.1), nlpar = "min", class = "sd"), # corresponds to variance of 100
  prior(exponential(0.1), nlpar = "max", class = "sd"), # corresponds to variance of 100
  prior(exponential(0.05), nlpar = "slope", class = "sd"), # corresponds to variance of 400, much wider to capture possibly flat/negative slopes
  prior(exponential(1), nlpar = "X0", class = "sd"), # corresponds to variance of 1
  prior(exponential(1), dpar = "sigma", class = "sd") # for residual variance
)

brm.log.fit <- brm(
  formula = logistic.formula,
  data = as.data.frame(mld_filtered_matlab),
  family = gaussian(),
  prior = logistic.priors,
  cores = 4,
  chains = 4,
  iter = 6000,
  warmup = 2000,
  control = list(adapt_delta = 0.99),
  save_pars = save_pars(all = TRUE)
)
```


```{r save-Rdata}
# the model took nearly 12 hours to run, so I'm saving that shit into an Rdata file so I don't have to do it again

save(mld_filtered_matlab,
     logistic.formula,
     logistic.priors,
     brm.log.fit,
     file = "Rdata/vas-bayesian-curvefitting-fit.Rdata")
```

```{r}
# lemme try something quick

subset = mld_filtered_matlab %>%
  filter(day == "1", ID %in% c("102", "103", "104", "106", "107"))

brm.log.fit.subset <- update(brm.log.fit, newdata = as.data.frame(subset),
                              cores = 4, iter = 2000, warmup = 1000)

summary(brm.log.fit.subset)
```

