# Introduction {#ch1-intro}

```{r, include=FALSE}

# all that needs to be changed is seq_id in the run_autonum function, which restarts figure/table numbering with each chapter

# create functions for table and figure captions using officer functions

# these functions use the chunk label to enable cross-referencing with bookdown syntax 

table_caption <- function(caption){
  block_caption(label = caption,
              style = "Table Caption",
              autonum = run_autonum(seq_id = "chp1tab", 
                       pre_label = "Table ", 
                       tnd = 1, tns = ".", 
                       bkm = opts_current$get("label"),
                       prop = fp_text_lite(bold = TRUE)))
}

figure_caption <- function(caption){
  block_caption(label = caption,
              style = "Image Caption",
              autonum = run_autonum(seq_id = "chp1fig", 
                       pre_label = "Figure ", 
                       tnd = 1, tns = ".", 
                       bkm = opts_current$get("label"),
                       prop = fp_text_lite(bold = TRUE)))
}

# an alternative to include_graphics - figures are in their original aspect ratio (but huge in the output, usually like 200% so I might have to manually go in and change everything...)

officer_figure <- function(file){
fpar(external_img(file, guess_size = T), fp_p = fp_par_lite(word_style = "Figure", keep_with_next = T))
}
```


## Background and Motivation {#background}

Early in the foreign language learning process, one of the first difficulties adult learners face is accurately perceiving and producing the sounds of the target language. Specifically in the skill domain of listening, learners must perceptually identify and discriminate between new phonemes. The degree of difficulty of this problem is highly dependent on the similarities and differences between the sound inventories of the learners' first language(s) (L1s) and their target language. Nevertheless, learning new speech categories is difficult for adult learners who face interference from the already-mapped speech categories of their L1, as described by psycholinguistic models of speech category learning like the Perceptual Assimilation Model for L2 [PAM-L2: @Best2007Nonnative], the Revised Speech Learning Model [SLM-r: @Flege2021Revised], and the Revised Second Language Linguistic Perception Model [L2LP-revised: @vanLeussen2015Learning].

The challenge of learning foreign language speech sounds and phonemes has often been characterized as a category learning problem from perceptual and cognitive perspectives. Categorization and category learning are fundamental to language acquisition. Some cognitive scientists assert that phonetic categories are the "basic perceptual units of language" [@Myers2014Emergence] or the "target of learning" for second language (L2)[^introduction_chapter-1] speech acquisition [@Baese-Berk2022nature]. @Flege2021Revised define the role of phonetic categories as the medium by which meaningful speech segments are accessed during lexical access and as the representation of articulatory gestures of the language-specific phonology. With its place near the lowest level of the cognitive processing ladder, just above the perceptual processing step, a strong foundation of the phonetics and phonology of the target language is crucial in L2 speech processing. From this strong foundation, phonetic and phonological categories guide the processing and learning of other language structures and functions, such as word forms, grammar, semantics, syntax, lexicon, and sentence-processing to name a few [@Werker2005Infant]. Other work has noted the importance of lower-level perception and the integration of bottom-up and top-down processes that is needed for L2 listening [@Field2009Listening; @Field2003Promoting; @Siegal2015Getting; @Tsui1998Bottomup].

One of the main goals of speech categorization is to solve the problem of the lack of invariance, which describes the problem that there is generally no one-to-one mapping between particular acoustic signals and particular speech sounds [@Appelbaum1996lack; @Pisoni1995Variability]. The same word or speech sound can be uttered by different people, and even by the same person at different time points in different contexts, with remarkable variability in their acoustic attributes. These sounds can vary along continuous dimensions, such as duration, fundamental frequency (F0), amplitude, and so on. Yet, the dominant theoretical framework of speech categorization purports that the nature of speech is such that these acoustically variable speech signals must be mapped to the discrete speech sound units that are used to construct the mental lexicon [cf. @Goldinger1998Echoes; @Port2007How for examples of exemplar-based viewpoints that categorization is a process of comparing incoming stimuli to stored memory traces of speech].

Early speech perception research observed the phenomenon of categorical perception [@Liberman1957discrimination] and accepted it as the perceptual system's solution to the problem of the lack of invariance. Categorical perception (CP) describes the behavior of the auditory perceptual system that when listeners are asked to judge a continuum of speech stimuli that vary in equal steps along an auditory dimension between two speech categories (e.g., consonants /b/ vs. /p/), that the perceptual system seems to encode continuous acoustic information into discrete perceptual units or categories in such a way as to suggest that the perceptual system eliminates within-category differences and enhances between-category differences [@Harnad2003Categorical]. CP came to be seen as the goal of the perceptual system and the gold standard of L1 speech perception, especially given the evidence that the hallmark measures of categorical perception scaled with experience in L2. Highly experienced L2 speakers showed near-L1 like behaviors, but inexperienced L2 learners showed very poor categorical perception behaviors, presumed to have been due to poorly-defined category structures and boundaries in L2 learners [e.g., @MacKain1981Categorical].

However, even during the rise in popularity of the CP theoretical framework, some researchers found evidence that CP is not universal, neither across speech sounds nor individuals, suggesting that the perceptual system may be encoding within-category differences, or in other words, that at least some speech may be processed continuously instead of categorically [@Hary1982Categorical; @Massaro1983Categorical]. Some researchers have attempted to reframe speech perception as a process of categorization, which adds nuance to suggest that while the perceptual system needs to map variable acoustic signals to discrete speech categories, it may still do so while remaining sensitive to within-category differences [@Holt2010Speech; @McMurray2022myth]. Behavioral and physiological evidence from recent research has shown that listeners do in fact encode information gradiently and has supported the perspective that not only is the perceptual encoding of continuous acoustic information *not* a deficiency of the perceptual system, but it may actually be beneficial in L1 speech perception, for example, in cases of ambiguity [e.g., @Toscano2010Continuous; @Brown-Schmidt2017Gradient; @Desmeules-Trudel2019Gradient; @Kapnoula2021Gradient; @Kapnoula2021Idiosyncratic; @Ou2021Individual].

These works fall under a framework themed around gradiency, gradient perception, and gradient categorization. Gradient perception can be measured by a more gradient task, the visual analog scale (VAS), which mirrors the classical categorical perceptual identification tasks in asking listeners to judge a continuum of equally varying speech stimuli, except that the task allows listeners to pick anywhere on a continuous scale how much the presented stimulus sounds like one end or the other of the phonemic contrast continuum. The measurements from the VAS task provides parametric measurements of both slope and response variability that allows for the disambiguation between categorical, gradient, and noisy perceptual response patterns [@Apfelbaum2022Dont; @Kutlu2022Moving; @Sorensen2024Bayesiana].

Other work in gradient categorization has shown evidence of gradient perception strategies, disambiguated from noisy perception, in bilinguals [@Kutlu2022Moving]. This aligns with the idea that bilinguals need perceptual flexibility and adaptive acoustic cue integration to process both languages. This also aligns with evidence that individuals that tend to perceive speech more gradiently have been found to be more likely to integrate secondary cues in ambiguous speech perception [e.g., @Kong2011Individual; @Kong2016Individual; @Kapnoula2017Evaluating; @Kapnoula2021Gradient; @Kapnoula2021Idiosyncratic].

The role of gradient categorization in non-L1 perception and implications for L2 phonological learning is less clear. A few studies have explored how categorization gradiency and consistency for L1 speech may be correlated with L2 perception, learning, and proficiency. Some studies using naïve L1 listeners with no knowledge of the L2 found that categorization consistency correlated with success in the perception and learning of novel L2 contrasts but that gradiency had no influence [@Fuhrmeister2023Relationships; @Honda2024Exploring], while another study using naïve L1 listeners showed that those with more gradient categorization were more successful in learning L2 contrasts and reweighting acoustic cues to be more attuned to the L2 [@Lee2024Acoustic]. One study using highly proficient L2 listeners found that categorization gradiency, but not consistency, was correlated with L2 proficiency such that gradient categorization patterns in L1 was correlated with higher L2 vocabulary knowledge [@Kapnoula2024Sensitivity]. Fewer studies have measured categorization gradiency in both L1 and L2 speech within the same individuals. One study found that neither categorization gradiency in L1 nor L2 was correlated with L2 proficiency [@Kong2019Individual], while another study showed that more categorical perceptual patterns, rather than gradient perceptual patterns, were predicted by higher L2 proficiency [@Kong2023Individual]. These conflicting results may be attributed to differences in learner populations, implementation of the VAS task, analysis of gradiency, diversity of L2 proficiency, and operationalization of non-L1 learning and proficiency. It is clear that more research is needed to elucidate relationship between categorization gradiency and proficient L2 perception and learning.

Despite these mixed results, I hypothesize that gradient perception is relevant to L2 speech category learning given that L2 speech category acquisition necessitates processes such as category remapping through boundary shifting and category creation through cue integration, among other processes [for reviews, see @Baese-Berk2022nature; @Nagle2022Advancing]. Consequently, perceptual flexibility and adaptive acoustic cue integration may be advantageous for learning L2 speech categories. As gradient perception is correlated with perceptual flexibility and adaptive acoustic cue integration, this suggests that gradient perception may be advantageous for learning L2 speech categories.

Other work has shown that monolinguals who are exposed to more linguistically diverse social network show evidence of brain activity exhibiting sensitivity to foreign language lexical items [@Bice2019English]. Very recent results have shown that linguistically diverse social networks are highly predictive of gradient response profiles [@Kutlu2024Social]. Linguistic diversity here means the number of languages that the individual is exposed to from persons in their social network. This may suggest a bidirectional influential relationship between multilingualism and gradient categorization, such that being exposed to more languages may result in gradient perception and gradient perception may result in perceptual flexibility to enable the proficient processing of L2 speech sounds.

Of particular note is that this may not be a generalized "multilingual advantage" over monolingualism. One study found that bilinguals with knowledge of a language with a particular phonemic contrast better perceived an unrelated language that had a similar phonemic contrast, compared to bilinguals whose known languages did not have a similar contrast [@Patihis2015Phoneme]. That is, if a multilingual advantage for non-L1 perception exists, it might be limited to a narrower set of L2 contrasts. An interesting extension to this line of research is whether perceptual training with a non-target language that shares similar phonemic contrasts with a learner's target language can provide an additional advantage above and beyond exposure to broad, non-specific linguistic diversity.

## Research Questions {#RQs}

What still remains unclear in the literature is the degree to which gradient perception in L1 and L2 are connected, the degree to which gradient categorization is beneficial in the perception and learning of L2 contrasts, and whether the perceptual benefits of linguistic diversity and language experience can be simulated in naïve and experienced L2 learners through perceptual training with specific linguistic diversity. The present dissertation is guided by the following research questions in order to address these uncertainties:

**RQ1.** Is increased experience with linguistic diversity (hereafter, *experiential linguistic diversity*) from one's language history, usage, and exposure predictive of higher degrees of gradient categorization of L2 speech as it is with L1 speech? If so, do higher degrees of L2 gradient categorization predict the degree of usage of the secondary acoustic cue in the perception of L2 phonemic contrasts, as we see with L1 gradiency and secondary cue use?

**RQ2.** Can we promote gradient categorization in listeners through specific exposure to linguistic diversity via perceptual training? If so, does gradient categorization increase perceptual sensitivity to discriminate between target language phonemic contrasts?

**RQ3.** Does specific exposure to linguistic diversity through perceptual training lead to improvements in L2 speech perception and listening?

Broadly, the motivation for this dissertation project was to devise strategies to make the learning of new L2 speech sounds easier for adult learners of a foreign language. To this end, I experimented with a novel perceptual training method that makes use of linguistically diverse input as a way to improve perception of L2 categories that share common acoustic characteristics and to improve the perceptual discrimination of difficult L2 phonemic contrasts. This body of work contributes to the fields of applied linguistics and psycholinguistics by laying the groundwork for improved L2 pedagogy and theoretical advances in speech sound acquisition and learning.

## Chapters Overview {#overview}

This dissertation is organized into six chapters. Following this introductory chapter, Chapter 2 provides a detailed review of the relevant theoretical and empirical literature on the role of gradient categorization on speech perception and speech learning, the role of linguistic diversity and language experience in L2 speech perception and learning, and the target L2 phonemic contrast, ending with a statement of the specific aims. Chapters 3 through 5 presents the empirical research undertaken to answer the research questions and address the specific aims. Chapter 3 presents Study 1, which examined the relationship between experiential linguistic diversity, L1 and L2 categorization, and perceptual flexibility through secondary cue integration. Chapter 4 presents Study 2, which investigated the effects of short-term specific linguistic diversity perceptual training on L1 and L2 categorization and L2 phoneme discrimination. Chapter 5 presents Study 3, which explored the effects of long-term specific linguistic diversity perceptual training in addition to classroom instruction on L1 and L2 categorization, L2 phoneme discrimination, and L2 speech perception and listening. Finally, Chapter 6 presents the general discussion, where the findings across the three studies are summarized to consider theoretical and practical implications, discuss limitations, and offer avenues for future research.

## A Note on Transcription Conventions {#transciption}

Throughout this dissertation, the distinction between *phones* (language-agnostic) and *phonemes* (language-specific) is particularly relevant. As such, phones are denoted using phonetic transcription conventions, including square brackets [] and diacritics. Phonemes are denoted using phonemic transcription conventions, including slashes // and phonemic symbols. Throughout, I use Hepburn-style romanization for Japanese words. Hepburn romanization tends to follow English orthography for a few select consonants rather than systematically following Japanese phonology [@Gottlieb2010Romaji]. For example, for in the *hiragana* characters し [ɕi],じ [dʑi], ち [tɕi], and つ [tsɯ], the consonants [ɕ, dʑ, tɕ] are allophonic realizations of [s, z, t] before [i] for native Japanese words, and the consonant [ts] is an allophonic realization of [t] specifically before [ɯ] [@Labrune2012Phonologya]. In *Kunrei-shiki* (lit. 'cabinet style') romanization, another form of romanization often used by the Japanese government, these four characters would be transcribed as *si*, *zi*, *ti*, and *tu* to reflect their allophonic counterparts. However, using Hepburn romanization, these would be transcribed as *shi*, *ji*, *chi*, *tsu* as spellings that correspond with typical English pronunciations. To reflect geminated consonants for digraph characters, such as *sh*, *ch*, and *ts*, the first letter is doubled to produce *ssh*, *cch*, and *tts*. Out of ease, I choose to use Hepburn-style romanization, with the exception of transcribing vowel length, where I use double letters instead of the macron diacritic. When relevant, I distinguish phonologically long vowels from sequences of identical short vowels that arise at morphological boundaries using a period, e.g., 数理＝すうり [sɯːɾi] *suuri* 'mathematical theory' from *suu* 'numbers' and *ri* 'principle/logic' vs. 酢売り＝すうり [sɯɯɾi] *su.uri* 'vinegar seller' from *su* 'vinegar' and *uri* 'seller' [@Labrune2012Phonologya]. Romanized transcriptions of Japanese target words are italicized. Translated English glosses are in single quotes.

## Open Science Statement {#openscience}

In the enthusiastic interest of scientific transparency and reproducibility, the materials created and used in the undertaking of this dissertation project are freely available. For the static dissertation document, the appendix contains key study materials. The full collection of study materials, including stimuli and task materials, raw and cleaned anonymized data, and data analysis code, can be found in the supplementary materials available through the following webpages: [OSF Project](https://doi.org/10.17605/OSF.IO/M6T59) and [Gorilla Open Materials Page]( https://app.gorilla.sc/openmaterials/1089564). The supplementary materials may be continually updated at request. All data wrangling, analyses, and visualization were performed using R [v.4.4.3, @R-base].



[^introduction_chapter-1]: Note that the terms "second language" or "L2" will be used throughout to mean any non-L1 language(s) learned after adolescence, which may not necessarily be the actual second language learned.
